# §1.47 Formalization Tracker

## Status: Build green; **3 faithful `sorry`s remaining**.  This pass ASSEMBLED the §1.472
## keystone `prodEndo_faithful_iff_product_proper` as the §1.453 specialization to `T = prodEndo B`.
## The keystone biconditional is now CORRECTLY STATED and its backward direction (RHS ⟹ Embedding)
## is FULLY PROVEN; the keystone no longer carries its own open mathematical gap — it reduces
## entirely to the single new lemma `prodEndo_faithful_of_embedding` (see below).

## THIS PASS (Opus) — §1.472 keystone assembly:
##  1. NEW sorry-free `prodEndo_preservesPullbacks` : `PreservesPullbacks (prodEndo B)`.  A cone
##     leg into `B×X` splits as `(b:·→B, x:·→X)`; `fst`-component forced equal, `snd`-component
##     gives a base cone over `(f,g)` whose lift paired with the common `B`-leg is the lift.
##  2. NEW sorry-free `prodEndo_preservesProductMonic` : `PreservesProductMonic (prodEndo B)`
##     via the three jointly-monic legs `fst`, `snd≫fst`, `snd≫snd`.
##  3. NEW sorry-free `prod_mono_swap_conj` + `isIso_prod_mono_iff` : the factor-order bridge
##     `m × id_B = prodSwap ≫ (id_B × m) ≫ prodSwap` (S1_42 `prodSwap`/`prod_comm_iso`),
##     giving `IsIso (m × id_B) ↔ IsIso (id_B × m)`.  This relates §1.453's `PreservesProperness`
##     (about `id_B × m`, the `B×-` direction) to the book's RHS (about `m × id_B`, `-×B`).
##  4. `prodEndo_faithful_iff_product_proper` now takes `[HasTerminal][HasBinaryProducts]`
##     `[HasPullbacks]` + `hB : ∃ B' n, ProperMono n` and is driven by §1.453
##     `pullback_faithful_iff_preserves_properness` fed the two preservation witnesses.
##       - (⟸) RHS ⟹ Embedding: FULLY PROVEN (RHS gives `PreservesProperness`, §1.453 gives
##         `Faithful`, `.1` is `Embedding`).
##       - (⟹) Embedding ⟹ RHS: proven modulo `prodEndo_faithful_of_embedding`.
##  5. The new `hB` guard is ESSENTIAL, not cosmetic: the unguarded forward biconditional is FALSE
##     (§1.475 Z-sets — `Z` has no proper subobject, `Z×-` is faithful, yet `id_Z × m` may be iso
##     for proper `m`).  `hB` is exactly Freyd's "every B WITH a proper subobject".  All call sites
##     (`special_iff_prodEndo_faithful`, `oneValued_special_iff`, `prodEndo_faithful_all_implies_special`,
##     `isSpecial_implies_prodEndo_faithful`) supply such a witness, and now also construct the
##     `[HasPullbacks]` instance from products+equalizers (`products_equalizers_implies_pullbacks`).

## The 3 remaining sorries are GENUINE mathematical residuals:
##  - `special_atMostTwoValues` (§1.471) — needs §1.646 faithful-representation-into-Set.
##  - `prodEndo_faithful_of_embedding` (§1.472 iso-reflection, the keystone's last gap) — proves
##    `Embedding (prodEndo B) + hB ⟹ Faithful (prodEndo B)`.  Partial proof IS in place: it
##    derives `Mono f` AND `f` epic from `snd`-epic (= Embedding) and `map f` iso.  The remaining
##    `sorry` is exactly `mono ∧ epic ∧ (proper subobject of B) ⟹ iso` — Freyd's §1.472 content.
##    A general Cartesian category is NOT balanced (§1.652/§1.913 give balancedness only in
##    pre-topoi/topoi), so monic+epic alone does not give iso; the proper subobject of B is the
##    essential extra ingredient (a point of B / split `snd` would suffice but is not available).
##  - `twoValued_special_prodEndo_faithful` (§1.474 ⟹) — now reduced (via new sorry-free
##    `fst_prodZero_mono`: `fst : B×0 → B` is monic) to the single sorry "properness of
##    `fst : B×0 → B` when `B ≇ 0`", which needs `B×0 ≅ 0` (the special dichotomy on `0 ↪ 1`).

## What changed THIS pass (Opus, §1.453 now proved in S1_45)
##  1. NEW `IsSpecial 𝒞` (predicate form of the `special` field over the *ambient* products) +
##     `IsSpecial.toSpecial` (builds the bundled class on the SAME ambient instance).  This is
##     the redraft that removes the wall: `CartesianCategory` carries the chosen `prod` as data,
##     so `Nonempty (SpecialCartesianCategory 𝒞)` under a separate ambient `[CartesianCategory]`
##     forces two distinct product structures into one goal — the conclusion `Embedding
##     (prodEndo B)` landed on the wrong one.  `IsSpecial` keeps one structure in scope.
##  2. Converted `special_iff_prodEndo_faithful`, `oneValued_special_iff`,
##     `twoValued_special_iff` to take `IsSpecial 𝒞` (was `Nonempty (SpecialCartesianCategory)`)
##     on the LHS.  All three `⟹` sorries DISCHARGED.
##  3. Converted helpers `oneValued_special_prodEndo_faithful`,
##     `twoValued_special_prodEndo_faithful` and added `isSpecial_implies_prodEndo_faithful` to
##     take `IsSpecial 𝒞` instead of `[SpecialCartesianCategory 𝒞]`, so the whole §1.473/§1.474
##     chain runs on the ambient products.

## Earlier pass status (retained below): the `twoValued_special_iff` `B ≅ 0` branch is a real
## sorry-free vacuity proof; `oneValued_special_prodEndo_faithful` and
## `prodEndo_faithful_all_implies_special` are sorry-free.

The local product endofunctor here is `prodEndo B : X ↦ prod B X` with `prodEndoIsFunctor`
its `Functor` instance (S1_85 has a separate `prodFunctor`; do not confuse them). Its action on
arrows is `prodEndo.map f = pair (fst ≫ id_B) (snd ≫ f) = pair fst (snd ≫ f)`.

## What changed this pass (Opus, §1.437/438 now sorry-free)

1. **New sorry-free lemma `prodEndo_map`** — definitional unfold of `(prodEndo B).map`.
2. **New sorry-free lemma `prodEndo_embedding_iff_snd_epi`** (the prompt's "clean reformulation"):
   `Embedding (prodEndo B) ↔ ∀ X Y (f g : X⟶Y), snd ≫ f = snd ≫ g → f = g`, i.e. `B×-` is faithful
   iff `snd : prod B X → X` is epic for every `X`.  Proof: `(B×-)f = (B×-)g` unfolds to a `pair`
   equality whose `snd`-component (via `snd_pair`) is exactly `snd≫f = snd≫g`; `pair_uniq` gives
   the converse.  Axioms: `propext` only.
3. **New sorry-free lemma `product_mono_of_mono`** — `Mono m ⟹ Mono (m × id_B)`, UNCONDITIONALLY
   (no specialness).  Axiom-free.  This *diagnosed and corrected* a bug:
4. **Corrected `prodEndo_faithful_iff_product_proper`** from `Mono (m × id_B)` to
   `ProperMono (m × id_B)`.  The old RHS was a **tautology** (every `Mono m` gives `Mono (m×id_B)`
   by `product_mono_of_mono`), so the old `↔` was simply FALSE — its LHS `Embedding (prodEndo B)`
   fails in non-special categories (§1.475 Z-sets) while the old RHS always held.  The book
   (§1.472) demands `A'×B` be a **proper** subobject of `A×B`; `ProperMono` restores fidelity.
   The non-iso (properness) half is the substantive content and remains `sorry`.

## Sections

| Section | Topic                                     | Decl(s)                                    | Status  |
|---------|-------------------------------------------|--------------------------------------------|---------|
| §1.442  | Cayley preserves/reflects pullbacks        | `cayley_preserves_pullback`                | proved  |
|         |                                           | `cayley_reflects_pullback`                 | proved  |
|         | Cayley preserves/reflects equalizers       | `cayley_preserves_equalizer`               | proved  |
|         |                                           | `cayley_reflects_equalizer`                | proved  |
| §1.444  | Horn sentences transfer via Cayley         | `hornSentence_transfer`                    | proved  |
| §1.47   | Special Cartesian category (definition)    | `ProperMono`, `SpecialCartesianCategory`   | proved  |
| §1.47   | special predicate / class bridge           | `IsSpecial`, `IsSpecial.toSpecial`         | proved (NEW) |
| §1.471  | Special ⇒ at most two values              | `special_atMostTwoValues`                  | sorry (§1.646) |
| §1.472  | Characterization via B×- faithful          | `prodEndo`, `prodEndoIsFunctor`            | proved  |
|         | reformulation: faithful ↔ snd epic         | `prodEndo_map`, `prodEndo_embedding_iff_snd_epi` | proved |
|         | `Mono m ⟹ Mono (m×id_B)` (unconditional)   | `product_mono_of_mono`                     | proved |
|         | `prodEndo B` preserves pullbacks           | `prodEndo_preservesPullbacks`              | proved (NEW) |
|         | `prodEndo B` preserves product-monicity    | `prodEndo_preservesProductMonic`           | proved (NEW) |
|         | factor-order bridge (B×- vs -×B)           | `prod_mono_swap_conj`, `isIso_prod_mono_iff` | proved (NEW) |
|         | keystone (§1.453 specialized)              | `prodEndo_faithful_iff_product_proper`     | (⟸) proved; (⟹) mod `_of_embedding` |
|         | Embedding+propersubobj ⟹ Faithful          | `prodEndo_faithful_of_embedding`           | sorry (Mono+Epic proven; iso=balanced step) |
|         |                                           | `special_iff_prodEndo_faithful` (IsSpecial)| proved (mod `_of_embedding`) |
| §1.473  | One-valued: special ↔ B×- faithful ∀B     | `OneValued`                                | proved  |
|         |                                           | `prodEndo_faithful_all_implies_special`    | proved  |
|         |                                           | `oneValued_special_prodEndo_faithful`      | proved (now IsSpecial) |
|         |                                           | `oneValued_special_iff` (IsSpecial)        | proved (NEW; mod keystone) |
| §1.474  | Two-valued: special ↔ B×- faithful ≠0     | `TwoValued`                                | proved  |
|         | `fst : B×0 → B` monic (0 subterminal)       | `fst_prodZero_mono`                        | proved (NEW) |
|         |                                           | `twoValued_special_prodEndo_faithful`      | sorry (only: `fst:B×0→B` proper, needs B×0≅0) |
|         |                                           | `twoValued_special_iff` (⇐, `B≅0` branch)  | proved  |
|         |                                           | `twoValued_special_iff` (⇒, IsSpecial)     | proved (NEW; mod keystone) |
| §1.48   | Dense class of monics                      | `DenseClass`, `DenseMonic`                 | proved  |
|         | Fraction spans                             | `Fraction`, `FractionEquiv`                | proved  |
|         | Rational category                          | `RationalCategory`                         | proved  |

¹ `oneValued_special_iff` has a `sorry` call in the (⇒) branch; the (⇐) branch is proved via
  `prodEndo_faithful_all_implies_special`.  The (⇒) `sorry` is **not** a missing math fact —
  `oneValued_special_prodEndo_faithful` already supplies the content — it is a Lean **instance
  coherence** wall (see below).
³ `twoValued_special_iff` (⇒) is the same instance-coherence wall as ¹.

## RESOLVED THIS PASS — §1.472/§1.473/§1.474 (⇒): the instance-coherence wall is gone

The wall below was real but was a *statement* defect, dissolved this pass by the `IsSpecial`
predicate redraft (see "What changed THIS pass").  The three `⟹` directions now carry no sorry of
their own; they reduce to the single §1.472 keystone (`prodEndo_faithful_iff_product_proper`), so
`#print axioms oneValued_special_iff` still shows `sorryAx` *transitively* until the keystone is
discharged — that is honest (these are book corollaries of §1.472), not a hidden wall.  Original
diagnosis retained for the record:

## §1.473/§1.474 (⇒) branches: an instance-coherence wall, not a missing proof

`oneValued_special_iff` and `twoValued_special_iff` are stated with an **ambient**
`[CartesianCategory 𝒞]` together with `Nonempty (SpecialCartesianCategory 𝒞)` on the LHS.
`CartesianCategory` carries data (`HasBinaryProducts.prod : 𝒞 → 𝒞 → 𝒞`, the *chosen* product
object), so the ambient instance and the one inside the `SpecialCartesianCategory` are two
genuinely-different structures — `prod B X` is a literally-different object for each. When the
(⇒) branch unpacks `⟨hS⟩` and calls `oneValued_special_prodEndo_faithful` (which needs
`[SpecialCartesianCategory 𝒞]`), Lean reports
`OneValued … inst✝` vs `OneValued … hS.toCartesianCategory` — the conclusion
`Embedding (prodEndo B)` it produces uses `hS`'s products, but the goal wants the ambient
products. `HasBinaryProducts` is **not** a subsingleton (verified: `prod` is data), so no
coherence bridge exists. The fix is a **statement redraft** (drop the ambient
`[CartesianCategory 𝒞]` and let the LHS `SpecialCartesianCategory` supply the products, so a
single product structure is in scope), which is outside the header fence for this pass. Flagged
`next_action = redraft` for `oneValued_special_iff` (⇒), `twoValued_special_iff` (⇒), and
`special_iff_prodEndo_faithful` (⇒) — all three share this exact wall.

## NEW this pass: `twoValued_special_iff` (⇐), the `B ≅ 0` branch — real proof, sorry-free

The remaining `B ≅ 0` branch is **vacuous**, and the proof discharges it by `exfalso`:
- `zeroObj` is a subterminator (`h2v.zero_proper.1 : Mono (term zeroObj)`), so every hom into
  `zeroObj` is a subsingleton (two maps agree after the monic `term zeroObj`, and any two maps
  into `one` agree by `term_uniq`).
- `_e : B → zeroObj` is iso (this branch's hypothesis), hence monic (`mono_of_retraction`); with
  `n` monic, `n ≫ _e : B' → zeroObj` is monic.
- A monic *into* a subterminator forces the **source** `B'` to have subsingleton hom; in
  particular `Mono (term B')`.
- Case `IsIso (term B')` (`B' ≅ 1`): a section `s1 : 1 → B'` gives `s1 ≫ (n ≫ _e) : 1 → zeroObj`,
  a section of `term zeroObj`; with `term zeroObj` monic this makes `term zeroObj` an iso,
  contradicting `h2v.zero_proper.2`.
- Case `¬IsIso (term B')`: `ProperMono (term B')` holds, so `h2v.zero_uniq` gives an iso
  `e' : B' → zeroObj`; by hom-subsingleton `e' = n ≫ _e`, so `n ≫ _e` is iso, hence `n` is iso
  (`isIso_comp` with `e_inv`), contradicting `hn.2`.

Both cases close `False`. Axioms: `Classical.em` only (already used pervasively in this file).
² Statement CORRECTED this pass from `Mono (m×id_B)` (a tautology — see `product_mono_of_mono`)
  to `ProperMono (m×id_B)`, matching the book's "proper subobject". The proof remains `sorry`.

## Why the sorries — the SHARPENED shared blocker (§1.453 + §1.646), re-diagnosed this pass

The prior tracker blamed `S1_43`'s two open `sorry`s. That is now **stale**: with
`S1_43` fully sorry-free (the §1.437/438 `CartesianFunctor` API — `cartesianFunctor_preserves_
pullbacks`, `pullbacks_terminal_implies_cartesianFunctor`, `reflects_equalizers_reflects_isos`
— all proved), I re-examined every §1.471–§1.474 `sorry`. **§1.437 is the tooling, not the
keystone.** The actual blocker is two-fold and lives OUTSIDE this file:

1. **§1.453 Lemma** (`pullback_faithful_iff_preserves_properness`, S1_45:295) — *"if `T` preserves
   pullbacks then `T` is faithful iff `T` preserves properness of subobjects."* This is **still a
   `sorry` in S1_45** (out of scope for this task; S1_45 is not editable here). The §1.472 bridge
   `prodEndo_faithful_iff_product_proper` is *exactly* §1.453 specialized to `T = prodEndo B`,
   which additionally needs `prodEndo B` to preserve pullbacks (also unproved). `monic_iff_kp_diag_
   iso` (S1_45, proved) is the right tool for §1.453 but the generic lemma is not assembled.
2. **§1.646 representation existence** — `special_atMostTwoValues` (§1.471) and the original
   definition of "special" (every universal Cartesian sentence transfers from Set) need a
   *faithful Cartesian representation `A → Set`* that preserves properness. §1.462 sketches the
   evaluation functors `E_A : Set^A → Set` as such, but **no representation-existence theorem
   is formalized anywhere in the repo** (grep for `1.646` finds only prose). Without it the
   universal-sentence transfer cannot be performed.

So every one of the eight statements routes through (1) or (2). Both are out of scope (S1_45 /
§1.646 are other files / unwritten). Fabricating them (`:= trivial`, vacuous restatements,
`Mono`-instead-of-`ProperMono` tautologies) would violate the integrity rule; the faithful
`sorry`s are kept, now with the correct blocker recorded.

### Per-sorry routing to the blocker (updated this pass)
- `prodEndo_faithful_iff_product_proper` → needs blocker (1) [§1.453 for `T=prodEndo B`]; the
  (⇒) direction additionally hits the "right inverse lives in `B×A`, not `A`" obstruction.
- `twoValued_special_prodEndo_faithful` → needs a proper subobject of `B` from "B≇0", i.e. the
  zero-object product iso `B×0 ≅ 0` (absent; would need §1.474 transfer / §1.646).
- `special_atMostTwoValues` → needs blocker (2) [§1.646 / Set transfer].
- `special_iff_prodEndo_faithful` (⇒), `oneValued_special_iff` (⇒), `twoValued_special_iff` (⇒)
  → **instance-coherence wall** (see dedicated section above); `next_action = redraft`, NOT a
  missing math fact. Their content already exists (`special_implies_prodEndo_faithful`,
  `oneValued_special_prodEndo_faithful`).
- `prodEndo_faithful_all_implies_special`, `oneValued_special_prodEndo_faithful` →
  **now proved sorry-free** (no longer route to any blocker).
- Additionally, blocker (1) for the §1.473/§1.474 *converse* directions needs a **product-swap
  iso** `prod A B ≅ prod B A` (the `special` field puts `B` on the right, `prodEndo` on the
  left); the repo still has none. Pure bookkeeping, but absent.

### Concrete diagnostics performed this pass (these CORRECT the prior tracker)

- **Reformulation proved** (`prodEndo_embedding_iff_snd_epi`): `prodEndo.map f =
  pair (fst≫id_B) (snd≫f)`; `map f = map g` post-composed with `snd` gives (by `snd_pair`)
  `snd≫f = snd≫g`, and `pair_uniq` gives the converse. So
  **`Embedding (prodEndo B) ↔ ∀ X, (snd : prod B X → X) is epic`** — now a real lemma in the
  file (not just prose). Axioms: `propext`.
- **CORRECTION to the prior tracker.** It claimed "`m × id` is *not* monic from `m` monic
  alone." That is FALSE: `product_mono_of_mono` proves `Mono m ⟹ Mono (m × id_B)`
  unconditionally and axiom-free, because `(m×id)≫fst = fst≫m` (recover the `fst`-component by
  `m`-cancellation) and `(m×id)≫snd = snd`, and `fst,snd` are jointly monic. Consequence: the
  original `prodEndo_faithful_iff_product_proper` RHS (`Mono (m×id_B)`) was a **tautology**, so
  the original `↔` was outright FALSE. Fixed by upgrading the RHS to `ProperMono`, per the
  book's "proper subobject" (§1.472). The substantive (non-iso) half is the §1.453 bridge.
- Factor-order mismatch persists: `special` uses `prod A' B` (B right) while `prodEndo B X =
  prod B X` (B left); no product-swap iso `pair snd fst` exists in the repo. This is now
  understood as a *secondary* (bookkeeping) gap; the primary gap is §1.453 + §1.646 above.

### Per-statement notes (routing summarised in "Per-sorry routing" above)

- **`prodEndo_faithful_iff_product_proper`** (§1.472): = §1.453 (`pullback_faithful_iff_preserves_
  properness`, S1_45 `sorry`) specialised to `T = prodEndo B`, + "`prodEndo B` preserves
  pullbacks". `monic_iff_kp_diag_iso` (proved, S1_45) is the engine but §1.453 isn't assembled.
- **`special_iff_prodEndo_faithful`** (§1.472): the per-`B` bridge above, both directions.
- **`prodEndo_faithful_all_implies_special`** (§1.473 ⇐): bridge forward (faithful ⇒ proper)
  + swap iso to land in the `special` field's factor order.
- **`oneValued_special_prodEndo_faithful`** (§1.473 ⇒): `1×-` faithful; if B≇1, `diag : B→B×B`
  proper (else `term B` monic, contra one-valued+B≇1) ⇒ `(B×B)×-` faithful ⇒ `B×-` faithful via
  composite `B×B×- = (B×-)∘(B×-)`. Needs the bridge to turn "diag proper" into faithfulness.
- **`twoValued_*`** (§1.474): `r : B×0 → 0` iso ∀B; `B×0 ↪ B×1 ≅ B` proper iff B≇0. Needs the
  zero-object product iso (`B×0 ≅ 0`, absent) + the bridge.

## Proved without sorry

- **NEW (this pass)** `twoValued_special_iff` (⇐) `B ≅ 0` branch — the vacuity proof above.
- **NEW (this pass, confirmed)** `oneValued_special_prodEndo_faithful`,
  `prodEndo_faithful_all_implies_special` — fully sorry-free (tracker previously stale).
- `prodEndo_map`, `prodEndo_embedding_iff_snd_epi`, `product_mono_of_mono` (see above).
- `prodEndo` (definition) + `prodEndoIsFunctor` (Functor instance): `map_id` via `pair_uniq` +
  `Cat.id_comp/comp_id`; `map_comp` via `Cat.assoc` + `fst/snd_pair`.
- `OneValued` and `TwoValued` (definitions): data/prop types, no proof obligation.
- All §1.442, §1.444, §1.48 content: proved in earlier commits.
