import Fredy.S1_1
import Fredy.S1_24
import Fredy.S1_39
import Fredy.S1_8
import Fredy.S1_9
import Fredy.S1_18
import Fredy.S1_81
import Fredy.S1_85
import Fredy.ToposDistributive
import Fredy.S1_91
import Fredy.S1_92
import Fredy.PartialMapClassifier
import Fredy.S1_94
import Fredy.S1_97
import Fredy.S1_26
import Fredy.S1_27
import Fredy.S1_41
import Fredy.S1_42
import Fredy.S1_44
import Fredy.S1_45
import Fredy.S1_47
import Fredy.Horn
import Fredy.Initial
import Fredy.S1_51
import Fredy.S1_52
import Fredy.S1_53
import Fredy.SliceRegular
import Fredy.SliceTopos
import Fredy.SlicePower
import Fredy.SlicePi
import Fredy.BaseChangeDescent
import Fredy.S1_55
import Fredy.S1_36
import Fredy.S1_54
import Fredy.S1_58
import Fredy.S1_59
import Fredy.AbCategory
import Fredy.AbAbelian
import Fredy.AbRegular
import Fredy.ExactRepresentation
import Fredy.S1_60
import Fredy.S1_70
import Fredy.S1_56
import Fredy.S1_57
import Fredy.S1_62
import Fredy.S1_64
import Fredy.S1_65
import Fredy.Diaconescu
import Fredy.S1_72
import Fredy.S1_14
import Fredy.S1_74
import Fredy.S1_75
import Fredy.S1_77
import Fredy.S1_82
import Fredy.S1_84
import Fredy.S1_95
import Fredy.ToposRTC
import Fredy.ToposColimits
import Fredy.ToposIndexedJoins
import Fredy.ToposExists
import Fredy.ToposCopowers
import Fredy.DirectedColimit
import Fredy.WellOrdering
import Fredy.CatColimit
import Fredy.CatColimitRegular
import Fredy.Capitalization
import Fredy.CapitalizationTransfinite
import Fredy.RelativeCapitalization
-- §1.543 capitalization: the FULL sorry-free closure of `Freyd.capData_exists`.  `CapDataWiring`
-- discharges `∀ A, Nonempty (CapData A)` by the §1.547 uniform cofinal successor (`uniformStep`) plus
-- the §1.546 fibre-density obligation, and transitively imports the whole cofinal-route stack:
--   UniformCapStep → UniformWellPoints → FibreDensityProof → CapDataWiring (all sorry-free).
-- `capData_exists`/`capitalization_lemma` are LIVE here; `#print axioms` = [propext, Classical.choice,
-- Quot.sound].  (The alternative §1.547 `PairObj` route — `RationalCapitalization`/`SliceWellPointed` —
-- is NOT imported; it carried isolated sorries and is unreachable from this chain.)
import Fredy.CapitalizationLaxColimit
import Fredy.LaxColimitPreReg
import Fredy.CofinalHstage
import Fredy.RatCapPreReg
import Fredy.RatCapHcanon
import Fredy.RatCapStagePTC
import Fredy.CofinalProjSystem
import Fredy.UniformCapStep
import Fredy.UniformWellPoints
import Fredy.FibreDensityProof
import Fredy.CapDataWiring
import Fredy.LaxColimitImages
import Fredy.RatCapImages
import Fredy.CapDataRegular
import Fredy.PowerAllegoryFamily
import Fredy.StalkFamily
import Fredy.StalkDetect
import Fredy.TstarRegular
import Fredy.TstarConservative
import Fredy.StalkRepr
import Fredy.UnionFromCoproduct
import Fredy.ColimitPositive
import Fredy.Inflation
import Fredy.S2_1
import Fredy.S2_21
import Fredy.S2_2
import Fredy.S2_22
import Fredy.S2_22b
import Fredy.S2_3
import Fredy.S2_4
import Fredy.S2_43
import Fredy.S2_5
import Fredy.S1_38b
import Fredy.FiniteSeparation
import Fredy.Representation646
import Fredy.S1_13
import Fredy.S1_10
import Fredy.FunctorCategory
import Fredy.MapCat
import Fredy.Spl
import Fredy.MatrixAllegory
import Fredy.Locale
import Fredy.RelCat
import Fredy.S2_218
import Fredy.StalkConservative
import Fredy.S2_33
import Fredy.CapitalProjective